language: python
matrix:
  include:
  - python: 2.6
    env: TOXENV=py26
  - python: 2.7
    env: TOXENV=py27
  - python: 3.3
    env: TOXENV=py33
  - python: 3.4
    env: TOXENV=py34
install:
- if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.2.0 tox==3.1.3;
  fi
- pip install tox
script: tox
env:
  global:
    secure: lj0MbKNRhLrC5STQma3KaFu6ppMehITIB55Gn6XW6YRmYcGjCMjslv0FtQH5ANYtAmmmNxuDBOST0qkJxPWZgfM4p25CcMXw4Raw8Mnwuwz9B8NFqcVpJ8w7PbWC3rudvw9utkkB6tc51Dye8GSSSmscj0OQP/JA0JfWZvf+FAADaAKi3zi0GVpkaIufDGo3SUEosbq9TzEqi8VJgUl/qZc/rNS0jwkwIZAKPW0ZFZnpO/jyQo8c5D+HPDbh43ZzvtpPUoDqwIwKken4B+v3RmpI8qMKLeYcR9qPyI00bsAebLqiv5CdWvsJ28OchsMFNfpZ/5U7/DPIhehli3kgzhADZcK+fms0wJhSuy4kBKeWfyK1XjP0WbkyN8LjL1aMG8k1kVA1R+xT2Bf5w3NqMWU3TXBmZhpCqbtF7Zy1mZkx5ARuPX7WoVvE/Hp1oSbFhbn9vcHOrMYg6LmW48oif4J5wa8ugNB4lQzfs8q0+KVWv4UG5nOkFC0TXWWdDtam0uUo9Bu/HNuH+0xXgb/ixnMpzNbA7FmmErMsogmtrROdcm91S+iuI///4EvJGl6iSqBTDHK3gDzJJOsXiukOAj9IdyVYLvkGVsedK4ocyVLeOZ8EK5YhxW6Slp+4sEnCeXDJ/Hn1ctzdyrHyuFZyd1oF2nDB3YzhXjcGidwLp1c=
