language: python
matrix:
  include:
  - python: 2.6
    env: TOXENV=py26
  - python: 2.7
    env: TOXENV=py27
  - python: 3.3
    env: TOXENV=py33
  - python: 3.4
    env: TOXENV=py34
install:
- if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.2.0 tox==3.1.3;
  fi
- pip install tox
script: tox
