language: python
matrix:
  include:
  - python: 2.6
    env: TOXENV=py26
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
dist: trusty
install:
- pip install tox
script: tox
env:
  global:
    secure: h/mIlNADwAjtG7diWUmopvTwUMglqBs9++x9MBu7L9eDIfvxjwj64+3eYfcmyMT/Cirq5F2TQRahs/IzF+Fbmed2O5Aw0JK1V6ZAEEGhcTV6KrNFaX4IALLaOIwXJ1j8tdvhf+xuUEHy900gaL7+lKx67XZy4HmkRHe5wKijV2okY9QZruefq5irc0Fs9ojfYY7J5mBkUF3PbFpH+aRqEtIXrFFRFkC9jCETEblpAtZODWLPjxGZnZAIl1KZJo96AhXN73vyAgQMqbkK/59fin2G/oufh671kjHmCiG/xIgtlAmZRRYANbwCMutE/kBRwEMsDqUY4x5KuDBJI0I25Y/FeIwMdJOczddofTA3vK86CG0yZughdpGqKuYQ2lQaR2SJfU8l0qsCCQyyz2ruPYOxl2fe6U387n3S6phIQSBuoKxFDZS1HGwP8ZYimpg8z8UlHjAwdqtLXbh8WzG9TGpBD9aX3/RC8z1GGnLzYsoKvQ1WjydpvTu2zcCykcJcmkAmiw+0l2/Z/lqOyfuXjYX59xF85M0PDVC7QFsxcPZo5MG/ANa/2BrjXjtgINwKMeL+fw5rXny+5XzINiR0MOAsryqdc7TWtvUGULEjIRqgULNSLJ2Emb89Tbp5n6KdXUYeU/UWnRiLL/mFa06SPt1zALDev4ZzB2hF2jMEoDs=
